"""empty message

Revision ID: 4a9816bf7248
Revises: 1bee3d8cdfbe
Create Date: 2022-05-26 20:46:49.962815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a9816bf7248'
down_revision = '1bee3d8cdfbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estates', sa.Column('country', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estates', 'country')
    # ### end Alembic commands ###
