"""empty message

Revision ID: 7c5431d51f64
Revises: 4a9816bf7248
Create Date: 2022-05-31 14:33:16.346382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c5431d51f64'
down_revision = '4a9816bf7248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charters', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('charters', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('critiques', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('critiques', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('estate_images', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('estate_images', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('estate_types', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('estate_types', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('estates', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('estates', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('missives', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('missives', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('missives', 'updated_at')
    op.drop_column('missives', 'created_at')
    op.drop_column('estates', 'updated_at')
    op.drop_column('estates', 'created_at')
    op.drop_column('estate_types', 'updated_at')
    op.drop_column('estate_types', 'created_at')
    op.drop_column('estate_images', 'updated_at')
    op.drop_column('estate_images', 'created_at')
    op.drop_column('critiques', 'updated_at')
    op.drop_column('critiques', 'created_at')
    op.drop_column('charters', 'updated_at')
    op.drop_column('charters', 'created_at')
    # ### end Alembic commands ###
